### ISSUE TITLE
US 09

### ISSUE THREAD

**Issue by gleal17** [fga-eps-mds/2018.2-Roles#100]
**Descrição**
Eu como usuário gostaria de poder ter acesso a informações detalhadas do evento para poder ter uma maior compreensão sobre o mesmo.

**Critérios de Aceitação** 
- Deverá ter os seguintes campos:
  - [x] Descrição geral do evento
  - [x] Descrição detalhada com comidas e drinks que vão ser servidos
  - [x] Localização do evento com mapa interativo
  - [x] Contato dos organizadores
- Testada;

**Comment by Lcunha** [comment]
Atualizei descrição da issue.
