### ISSUE TITLE
US 11

### ISSUE THREAD

**Issue by kalliub** [fga-eps-mds/2018.2-Roles#102]
**Descrição**
Eu como Usuário gostaria de poder curtir e ver o número de curtidas de um evento para poder avaliá-lo.

**Critérios de Aceitação** 
- Deverá apresentar o número de curtidas atual;
- Deverá permitir acrescentar uma curtida particular;
- Testada;

**Comment by Lcunha** [comment]
Atualizei descrição da issue.

**Comment by Lcunha** [comment]
Issue necessita ser quebrada
