### ISSUE TITLE
US 14

### ISSUE THREAD

**Issue by kalliub** [fga-eps-mds/2018.2-Roles#105]
**Descrição**
Eu como Desenvolvedor gostaria de ter todas as funcionalidades integradas em uma única branch para poder aplicar a identidade visual do projeto.

**Tarefas :** 
- [x] Resolver possíveis conflitos;
- [x] Integrar todas as funcionalidades em uma única branch _'integration'_.

**Comment by gleal17** [comment]
@kalliub dei uma conferida, da uma olhada nos commits em roles-app/feed e roles-app/integration...
Aparentemente ta tudo certo. (@VictorRodriguesS0)

**Comment by Lcunha** [comment]
US bem detalhada. Parabéns @kalliub
