### ISSUE TITLE
Refatoração de código do Cadastro de Eventos no Front-End

### ISSUE THREAD

**Issue by VictorRodriguesS0** [fga-eps-mds/2018.2-Roles#124]
**Descrição**
O cadastro de eventos apresenta muita incossistências de usabilidade e erros nos cadastros.

**Tarefas :** 
- [x] Upload de imagens;
- [x] Validação de campos;
- [x] Returno de sucesso (ou não) para o usuário.

**Comment by VictorRodriguesS0** [comment]
Novo Link para API: http://roles-events.herokuapp.com

**Comment by kalliub** [comment]
Segundo a definição da API "Fetch", ela não rejeita o status do HTTP, mesmo que a resposta seja 404 ou 500. Isso causará uma mensagem de sucesso para o usuário, mesmo sem a postagem ter sido bem sucedida. Por isso, temos de usar outra API, e provavelmente a XMLHttpRequest.

**Comment by Lcunha** [comment]
@kalliub Tenta usar o axios

**Comment by kalliub** [comment]
@Lcunha Algum motivo relevante? Parece ser mais fácil de usar mesmo. Vou ver se ela se adequa ao que precisamos

**Comment by Lcunha** [comment]
@kalliub Facilidade de uso, atende a demanda e comunidade bem ativa. Além disso temos outros 3 grupos trabalhando com isso.

**Comment by Lcunha** [comment]
@kalliub Dê uma olhada nos outros repositórios também

**Comment by Lcunha** [comment]
@Lcunha Dei uma olhada e vi que podemos usar o cloudinary

**Comment by Lcunha** [comment]
@kalliub Ver como usa por favor

**Comment by Lcunha** [comment]
Vou abrir uma issue especifica para o bug de uploud de imagens. Essa ficará somente para refatoração do cadastro.

**Comment by kalliub** [comment]
Código funcionando, mas com o envio de foto comentado, pois estamos no aguardo do backend receber photo como URL e não como arquivo.
