### ISSUE TITLE
Refatoração de Código do Microsserviço de Comentários

### ISSUE THREAD

**Issue by Henrike100** [fga-eps-mds/2018.2-Roles#125]
**Descrição**
Partes do código não seguem regras como as do clean code e precisam ser refatoradas.
Os arquivos com necessidade de refatoração são:
- [x] votes/api.py
- [ ] comments/tests.py
- [ ] votes/managers.py
- [x] comments_microservice/settings.py
- [x] comments/models
- [x] votes/urls.py
- [x] comments/serializers.py
- [x] comments/views.py
- [x] votes/utils.py
- [x] comment_microservice/urls.py
- [x] manage.py

**Tarefas :** 
- [x] Refatorar código do microsserviço;

**Comment by Lcunha** [comment]
@Henrike100 Já deu PR ?

**Comment by Henrike100** [comment]
Só criei a issue, irei começa-la assim que terminar a de eventos.

**Comment by Lcunha** [comment]
@Henrike100 E por que as tarefas estão marcadas, logo deduzimos a conclusão das mesmas. Altera por favor.

**Comment by Henrike100** [comment]
A intenção era diz quais são os arquivos que precisam ser alterados, não quais já foram. Vou alterar.

**Comment by Lcunha** [comment]
@Henrike100 Entendi, pedi alteração devido ao padrão que é adotado no projeto. Obrigado

**Comment by VictorRodriguesS0** [comment]
@Lcunha já existe link para utilização no Front-End da API?

**Comment by Lcunha** [comment]
@VictorRodriguesS0 Claro, olhe as issues que falam disso
