### ISSUE TITLE
Editar microserviços de eventos para novo upload de imagens.

### ISSUE THREAD

**Issue by Lcunha** [fga-eps-mds/2018.2-Roles#131]
**Descrição**
Devido as solicitações da US16, o microserviço deverá ter atualizações. Ao invés de salvar a foto, vai apenas salvar o endereço do Cloudinary.

**Comment by kalliub** [comment]
@Henrike100, preciso que o backend aceite URL no campo photo.

**Comment by kalliub** [comment]
@Henrike100 Peço para que, quando a alteração tiver sido feita, me comunique, para colocar em funcionamento!

**Comment by Henrike100** [comment]
A mudança foi feita, farei o pull request para a branch "dev".
