### ISSUE TITLE
Refatoração de código dos comentários de eventos no Front-End

### ISSUE THREAD

**Issue by VictorRodriguesS0** [fga-eps-mds/2018.2-Roles#138]
**Descrição**
O cadastro de comentários ainda estava utilizando mock API e precisa ser reformulado para microsserviço atualizado.

**Tarefas :** 
- [x] Validação de campos;
- [x] Returno de sucesso (ou não) para o usuário.
- [x] Conectado com o novo microsserviço
- [x] Adicionado ActionSheet para futura implementção de edição e exclusão de comentários.

**Comment by Lcunha** [comment]
Issue necessita ser quebrada para melhor realização dos trabalhos.

**Comment by Lcunha** [comment]
@VictorRodriguesS0  Detalhe as realizaçãoes referentes a essa isssue que foram implementadas nessa sprint.

**Comment by VictorRodriguesS0** [comment]
@Lcunha Alterações detalhadas!

**Comment by kalliub** [comment]
Ainda no aguardo da resolução dessa issue pra poder trabalhar numa finalização da sessão de comentários.

**Comment by VictorRodriguesS0** [comment]
@kalliub as alterações podem ser feitas referenciando essa issue

**Comment by kalliub** [comment]
Edição ficou como Bug.
