### ISSUE TITLE
Estudar consumo da Api de login do Integra

### ISSUE THREAD

**Issue by Lcunha** [fga-eps-mds/2018.2-Roles#146]
**Descrição**
Estudar maneira de consumir api de login do Integra e observar exemplos já realizados, no app e nos microserviços.

**Tarefas :**
- [ ] Documentação;
- [ ] IndicaAi 
- [ ] iFood;

**Comment by VictorRodriguesS0** [comment]
Não consegui encontrar dentro das branchs do indica-aí nenhum avanço na parte de login.
Inclusive testei algumas delas e nenhuma estava implementado.

**Comment by VictorRodriguesS0** [comment]
Testei o Vendas-app e não consegui verificar o funcionamento do login deles.

**Comment by VictorRodriguesS0** [comment]
> Testei o Vendas-app e não consegui verificar o funcionamento do login deles

 O aplicativo apresenta mau funcionamento mesmo realizando as configurações recomendadas.
