### ISSUE TITLE
Atualização do feed de acordo com novos requisitos e API

### ISSUE THREAD

**Issue by kalliub** [fga-eps-mds/2018.2-Roles#149]
**Descrição**
O feed sofreu alterações para poder exibir separadamente os eventos que já passaram da data de hoje, e também atualmente se encontra conectado à API antiga.

**Tarefas**
- [x] Conectar Feed à nova API que se encontra no link: http://roles-events.herokuapp.com/events/
- [x] Exibir no feed principal apenas eventos que estão acontecendo "hoje" ou estão para acontecer.

**Comment by Lcunha** [comment]
Issue está sem Labels, Milestone, Releases e etc, edite por favor.
