### ISSUE TITLE
Solucionar problemas de UI/UX

### ISSUE THREAD

**Issue by kalliub** [fga-eps-mds/2018.2-Roles#164]
**Descrição**
Há informações faltando que melhore a interação e experiência do usuário com o app.

**Cadastro de eventos**
Foi notado que leva-se muito tempo e cliques para criação rápida de um simples evento.

_Tarefas_
- [x] Diminuir a quantidade de campos obrigatórios
- [x] Destacar campos obrigatórios no cadastro
- [x] Retirar campo de link para outras redes sociais do cadastro e do Profile de eventos.
- [x] Retirar campo linkReference do Back-end

> Campos Obrigatórios: Nome do evento, nome do organizador, endereço, data e hora, +18 e foto.

**Feed**
O usuário sentiu falta de saber quantos comentários existem em um determinado evento, sem a necessidade de entrar em detalhes.

_Tarefas_
- [x] Apresentar quantidade total de comentários em cada evento
- [x] Criar um endpoint no Back-end pra filtrar comentários por ID de eventos

**Comentários**
Qualquer usuário tem acesso a apagar qualquer comentário.

_Tarefas_
- [x] Desabilitar deleção de comentários de outros usuários, permitindo apagar apenas o próprio comentário.

**Comment by kalliub** [comment]
Necessito de alterações imediatas no back-end, pra poder testar as requisições corretamente no front-end.

**Comment by Lcunha** [comment]
@kalliub Descrição só não esta pior que o título mundial do palmeiras
