### ISSUE TITLE
Guia de Instalação não acessível

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2018.2-Roles#181]
**Describe the bug**
O guia de instalação, do README.md, quando clicado abre uma página de 404 NOT FOUND

**To Reproduce**
1. Go to README.md in 'https://github.com/fga-eps-mds/2018.2-Roles'
2. Click on 'https://github.com/fga-eps-mds/2018.2-Roles/blob/master/guia_de_instalacao.md'
3. See error

**Expected behavior**
Abertura de um arquivo MD com as informações de instalação do produto

**Screenshots**

![screenshot from 2018-12-04 20-50-38](https://user-images.githubusercontent.com/37380789/49478218-52f3c600-f806-11e8-877d-b5768aa0c1b9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 17.10, Artful Aardvark
 - Browser: Chrome
 - Version: 70

@RochaCarla

**Comment by Lcunha** [comment]
@MatheusBlanco Valeu pela contribuição, vamos corrigir.

**Comment by gleal17** [comment]
Issue resolvida com o PR #183.
