### ISSUE TITLE
Construir Documento Arquitetura

### ISSUE THREAD

**Issue by gleal17** [fga-eps-mds/2018.2-Roles#29]
Issue relacionada a construção de documento de Arquitetura.

**Objetivo:** 
 - Construir Documento de Arquitetura

 **Tarefas :** 
- [x] Estudar Arquitetura de Software;
- [x] Elaborar o documento de Arquiterura
- [x] Tópico 1
- [x ] Tópico 2
- [x] Tópico 3
- [ x] Tópico 4
- [ x] Tópico 5
- [x] Tópico 6
- [x] Tópico 7
- [ ] Revisar 

US Relacionado à feature #41

**Comment by raulvicto** [comment]
Estudando como fazer documento de arquitetura:
http://www.linhadecodigo.com.br/artigo/3343/como-documentar-a-arquitetura-de-software.aspx

**Comment by gleal17** [comment]
Descrição atualizada.
