### ISSUE TITLE
Feedback Inicial - Issues e Documentação

### ISSUE THREAD

**Issue by fepas** [fga-eps-mds/2018.2-Roles#34]
Olá pessoas! A Carla me pediu pra dar um feedback dos grupos, e aqui estou! 

# Roles

- ## *Issues*

#### **Comunicação**

Vocês estão estão se comunicando pouco nas *issues*.

Se comunicar pelas *issues* trás uma comunicação bem transparente do projeto de vocês, e ajuda na avaliação de como vocês estão lidando com as adversidades de cada *issue*. É bem interessante que informações importantes estejam sempre sendo discutidas nas *issues*, além das outras ferramentas de comunicação que vocês usam, como *Telegram*.

#### **Pontuação**

Vocês não estão utilizando o sistema de pontuação nas issues, aqui tem alguns links pra ajudar nisso:

- Detalhes sobre o método *Planning Poker*:

    http://www.metodoagil.com/planning-poker/

- Site para realizar o *Planning Poker* online:

    https://scrumpoker.online/

Eu particularmente prefiro fazer com *post-its*, mas vai da preferência da necessidade de cada grupo.

#### **Nomes**

As *issues* estão com bons nomes. É interessante a prática de padronizar os nomes, e vocês já fazem utilizando os verbos no infinitivo (que já seria a minha recomendação). Está tudo bem claro e simples como deve ser.

#### ***Labels***

As Labels estão um pouco "pobres", mas é normal para essa primeira etapa do projeto. Provavelmente eu faça um mini-guia para ajudar grupos que estão mal nisso, e consequentemente vai ajudar vocês!.

As issues de vocês estão bem nomeadas, bem explicativas, parabéns! Só precisam melhorar um pouco na comunicação e nas labels (◕‿◕✿)

- ## Documentação

#### **Documento de Visão**

O documento de visão de vocês está bem claro em mostrar o que é o problema, seus desdobramentos, e a forma de atuação do IndicaAi nesse problema.
Cumpre a função, está bem organizado, escrito e detalhado. Só acho que vocês podiam explorar mais sobre a parte dos eventos. Que eventos?

#### **Documento de Arquitetura**

No documento de arquitetura falta muita coisa ainda, não dá pra fazer uma avaliação ainda. Corram pra terminar com ele!

#### **Documentação Geral**

Não encontrei a documentação de vocês sobre as sprints. É preocupante pois essa documentação é chave na transparencia do projeto e avaliação da evolução e do trabalho de vocês.

- ## Considerações Finais

Vocês tem que melhorar em algumas coisas ainda, mas no geral vocês não estão muito mal. Corram com a documentação, pois ela é muito importante. Muito legal que o README de vocês já tem uma explicação sobre o projeto.
Só precisam corrigir alguns errinhos nas issues, mas estão no caminho certo! ◕‿◕

A Carla vai poder dar um feedback mais técnico pra vocês, mas espero ter ajudado na melhoria do
projeto de vocês de alguma forma. ( ⌒o⌒)人(⌒-⌒ )

[]s, @fepas

**Comment by Lcunha** [comment]
Obrigado pelo feedback
