### ISSUE TITLE
Aperfeiçoar habilidades em React-Native

### ISSUE THREAD

**Issue by Lcunha** [fga-eps-mds/2018.2-Roles#41]
**Descrição**
Construir usando React Native um login e crud de usuário.

**Tarefas :** 
- [ ] Repositório no GIT particular;
- [ ] GitFlow no repositório;
- [ ] Link do repositório na issue;
- [ ] Ambiente básico React-Native;
- [ ] Autentificação;
- [ ] Cadastro de Usuário;
- [ ] Visualização de Usuários;
- [ ] Atualização de Usuários;
- [ ] Remoção de Usuários;

**Comment by gleal17** [comment]
Link do treino 
https://github.com/gleal17/treino_react.git

**Comment by VictorRodriguesS0** [comment]
Link para o treinamento em andamento:
https://github.com/VictorRodriguesS0/treino-react-native.git

**Comment by Henrike100** [comment]
**Tarefas :** 
- [ ] Repositório no GIT particular;
- [ ] GitFlow no repositório;
- [ ] Link do repositório na issue;
- [ ] Ambiente básico React-Native;
- [ ] Autentificação;
- [ ] Cadastro de Usuário;
- [ ] Visualização de Usuários;
- [ ] Atualização de Usuários;
- [ ] Remoção de Usuários;

**Comment by nicaloribeiro** [comment]
**Descrição**
Construir usando React Native um login e crud de usuário.

**Tarefas :** 
- [ ] Repositório no GIT particular; -- https://github.com/nicaloribeiro/treinamento-react-native
- [ ] GitFlow no repositório;
- [ ] Link do repositório na issue;
- [ ] Ambiente básico React-Native;
- [ ] Autentificação;
- [ ] Cadastro de Usuário;
- [ ] Visualização de Usuários;
- [ ] Atualização de Usuários;
- [ ] Remoção de Usuários;

**Comment by kalliub** [comment]
**Descrição**
Construir usando React Native um login e crud de usuário.

**Tarefas :** 
- [x] Repositório no GIT particular;
- [x] GitFlow no repositório;
- [x] Link do repositório na issue; -- https://github.com/kalliub/treino-react
- [x] Ambiente básico React-Native;
- [ ] Autenticação;
- [ ] Cadastro de Usuário;
- [ ] Visualização de Usuários;
- [ ] Atualização de Usuários;
- [ ] Remoção de Usuários;

**Comment by VictorRodriguesS0** [comment]
[Vídeo para ajudar a fazer a tela de login](https://www.youtube.com/watch?v=4TruGz_JVp8&t=37s)

**Comment by raulvicto** [comment]
> **Descrição**
> Construir usando React Native um login e crud de usuário.
> 
> **Tarefas :**
> 
>     * [ ]  Repositório no GIT particular;
> 
>     * [ ]  GitFlow no repositório;
> 
>     * [ ]  Link do repositório na issue;
> 
>     * [ ]  Ambiente básico React-Native;
> 
>     * [ ]  Autentificação;
> 
>     * [ ]  Cadastro de Usuário;
> 
>     * [ ]  Visualização de Usuários;
> 
>     * [ ]  Atualização de Usuários;
> 
>     * [ ]  Remoção de Usuários;

**Comment by raulvicto** [comment]
**Descrição**
Construir usando React Native um login e crud de usuário.

**Tarefas :** 
- [ ] Repositório no GIT particular;
- [ ] GitFlow no repositório;
- [ ] Link do repositório na issue;
- [ ] Ambiente básico React-Native;
- [ ] Autentificação;
- [ ] Cadastro de Usuário;
- [ ] Visualização de Usuários;
- [ ] Atualização de Usuários;
- [ ] Remoção de Usuários;
