### ISSUE TITLE
Feedback EPS

### ISSUE THREAD

**Issue by victorcmoura** [fga-eps-mds/2018.2-Roles#46]
# Feedback EPS

Opa, pessoal. Dei uma olhada no repo de vocês e tenho algumas considerações a fazer. 

### Comentários
Tentem comentar mais nas issues, expor dúvidas técnicas demonstra que está acontecendo trabalho contínuo. Não consegui enxergar muito bem o que tem sido feito desde a ultima vez que eu passei por aqui. Talvez isso seja apenas um problema de transparência.
### Milestones
Coloquem as datas das milestones, sem elas o ZenHub perde grande parte da sua utilidade.
![image](https://user-images.githubusercontent.com/26290053/45507098-84a94380-b767-11e8-8b0d-bfe4aeb76df7.png)
### Pontuação
A margem de pontuação de vocês merece uma revisão. Direi o que é possível interpretar dadas as pontuações abaixo:
![image](https://user-images.githubusercontent.com/26290053/45507238-e10c6300-b767-11e8-8d78-11d137188213.png)

- O esforço necessário para se construir um Documento de Arquitetura é metade do necessário para se fazer o roadmap dos papéis
- Criar o roadmap dos papéis exige o mesmo esforço que aperfeiçoar habilidades no React
- Construir a EAP é 5x mais fácil que criar o roadmap dos papeis

Caso os pontos acima estejam realmente acontecendo, procurem os monitores ou a professora para se orientarem melhor sobre a criação do roadmap. Me coloco à disposição para ajudá-los, mas repito que o documento enviado no comentário da [issue](https://github.com/fga-eps-mds/2018.2-Roles/issues/23) pode ajudá-los nesta tarefa.

## Código
Comecem o código assim que possível. Mesmo sem total confiança técnica ou escopo definido, um initial project com ambiente de teste configurado já é o suficiente para adiantar questões como:
- Ambiente de desenvolvimento dos MDS
- Configuração do pipeline de produção

Mesmo que não dê tudo certo de primeira, o importante é errar o mais cedo possível para corrigir o erro o mais cedo possível ;D

Qualquer dúvida, podem procurar os monitores ou a professora. Abraços e bom trabalho! xD

**Comment by Lcunha** [comment]
@victorcmoura Obrigado feedback, vou adequar o repositório de acordo com o sugerido.
