### ISSUE TITLE
Update nodejs v8.12.0

### ISSUE THREAD

**Issue by gleal17** [fga-eps-mds/2018.2-Roles#53]
**Descrição**
Atualizar Nodejs para versão v8.12.0 (LTS) 

**Problema**
`nodejs --version` (v4.2.x )
Nodejs não atualiza via apt-get e matinha versão default.

**Tarefas :** 
- [ ] 1.Criar arquivo como sudo: `/etc/apt/sources.list.d/nodesource.list`
Inserir no arquivo:
```
deb https://deb.nodesource.com/node_8.x xenial main
deb-src https://deb.nodesource.com/node_8.x xenial main
```
*Note que 8.x é a versão que deseja utilizar
- [ ] 2. Download  GPG Signing Key de Nodesource. (resolve problema apt-get)
```
curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
```
- [ ] 3. Run `sudo apt-get update`
Se retornar NO_PUBKEY GPC error, volte ao passo 2.

- [ ] 4. Confira a saída de:
`apt-cache policy nodejs`

> nodejs:
  Instalado: 8.12.0-1nodesource1
  Candidato: 8.12.0-1nodesource1
  Tabela de versão:
 *** 8.12.0-1nodesource1 500
        500 https://deb.nodesource.com/node_8.x xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     4.2.6~dfsg-1ubuntu4.2 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages

- [ ] 5. Instalar binário nodejs:
`sudo apt-get install nodejs` ou `sudo apt-get upgrade
`
- [ ] 6. Confira no terminal:
`nodejs --version`

**Comment by gleal17** [comment]
@VictorRodriguesS0 @iagoomr

**Comment by VictorRodriguesS0** [comment]
Devidamente atualizado, eu ja esta com a versão 8.11
Precisei apenas usar o comando 

`sudo apt-get upgrade`

`nodejs -v` para verficar a versão

![nodejs](https://user-images.githubusercontent.com/20848512/45554948-defcdf80-b80d-11e8-9cbb-065c202d8ecc.png)

**Comment by iagoomr** [comment]
Atualizado!

**Comment by kalliub** [comment]
O meu funciona sem precisar atualizar pro 8.
