### ISSUE TITLE
US03

### ISSUE THREAD

**Issue by kalliub** [fga-eps-mds/2018.2-Roles#82]
**Descrição**
Eu como Desenvolvedor gostaria de protótipos de baixa e alta fidelidade para base de construção do front-end.

**Critérios de Aceitação** 
- Deverá apresentar as telas de acordo com o que foi listado na seção Recursos do Produto no Documento de Visão
- Deverá ser apresentado com a ordem das telas conforme as funções forem sendo chamadas.
- Testada;

**Tarefas**
- [x] É testável;
- [x] Não é um épico. 
- [x] É estimável.;
- [x] Agrega valor ao negócio;

**Comment by Lcunha** [comment]
@kalliub Preso na está incorreta
