### ISSUE TITLE
US 05

### ISSUE THREAD

**Issue by Lcunha** [fga-eps-mds/2018.2-Roles#88]
Descrição
Eu como organizador gostaria de editar um evento para alcançar corrigir informações.

Critérios de Aceitação

    Deverá ter nome, organizador, valor, quantidade de vagas, local, foods, drinks e foto;
    Validação de campos.
    Microserviços.

**Comment by Henrike100** [comment]
# Campos que foram ditos na issue:

- [ ] Nome do Evento
- [ ] Organizador do Evento
- [ ] Valor
- [ ] Quantidade de vagas
- [ ] Local
- [ ] Foods
- [ ] Drinks
- [ ] Foto

# Campos que não foram ditos, mas aparecem no protótipo ou no aplicativo:

- [ ] Data do Evento
- [ ] Horário do Evento
- [ ] +18
- [ ] Descrição do Evento
- [ ] Link de referência
- [ ] Link da localização no Google Maps
- [ ] Telefone para contato

## Alguém, por favor, confirmar os campos necessários.

**Comment by Lcunha** [comment]
Atualizei descrição da issue.
